"""Add Web3 fields to User model

Revision ID: 2eaae97e03dd
Revises: bca6b6754ba4
Create Date: 2026-02-07 04:52:46.264176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaae97e03dd'
down_revision = 'bca6b6754ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eth_address', sa.String(length=42), nullable=True))
        batch_op.add_column(sa.Column('sui_address', sa.String(length=66), nullable=True))
        batch_op.add_column(sa.Column('nonce', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_sui_address', ['sui_address'])
        batch_op.create_unique_constraint('uq_user_eth_address', ['eth_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_eth_address', type_='unique')
        batch_op.drop_constraint('uq_user_sui_address', type_='unique')
        batch_op.drop_column('nonce')
        batch_op.drop_column('sui_address')
        batch_op.drop_column('eth_address')

    # ### end Alembic commands ###
